GastroApp/Areas/Admin/Controllers/ProduktController.cs
using GastroApp.Data;
using GastroApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace GastroApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator")]
    public class ProduktController : Controller
    {
        private ApplicationDbContext _db;

        public ProduktController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Produkty.Where(x=>x.Dostepnosc==true).ToList());
        }

        //Get Method 
        public IActionResult Create()
        {
            return View();
        }

        //Post Method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Produkt produkt)
        {
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Produkty.FirstOrDefault(c => c.Nazwa == produkt.Nazwa);
                if (searchProduct != null)
                {
                    ViewBag.mgs = "Taki produkt już istnieje!";
                    return View(produkt);
                }

                _db.Produkty.Add(produkt);
                await _db.SaveChangesAsync();
                TempData["success"] = "Produkt został dodany!";
                return RedirectToAction(nameof(Index));
            }
            return View(produkt);
        }

        //Get Method 
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = _db.Produkty.FirstOrDefault(x => x.IdProduktu == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        //Post Method 
        [HttpPost]
        public async Task<IActionResult> Delete(Produkt produkt)
        {
            produkt.Dostepnosc = false;
            _db.Produkty.Update(produkt);
            await _db.SaveChangesAsync();
            TempData["success"] = "Produkt został usunięty!";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = _db.Produkty.FirstOrDefault(x => x.IdProduktu == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        //Get Method 
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = _db.Produkty.FirstOrDefault(x => x.IdProduktu == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        //Post Method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Produkt produkt)
        {
            if (ModelState.IsValid)
            {
                _db.Produkty.Update(produkt);
                await _db.SaveChangesAsync();
                TempData["success"] = "Produkt został zedytowany!";
                return RedirectToAction(nameof(Index));
            }
            return View(produkt);
        }
    }
}

GastroApp/Views/Shared/_ButtonPartial.cshtml
@model int
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model" title="Edytuj"> <i class="bi bi-pencil"></i> </a>
        <a asp-action="Details" class="btn btn-warning" asp-route-id="@Model" title="Szczegóły"> <i class="bi bi-list"></i> </a>
        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model" title="Usuń"> <i class="bi bi-trash"></i> </a>
    </div>
</td>

GastroApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GastroApp</title>
    <!--Bootstrap Theme-->
    <link rel="stylesheet" href="~/css/BootTheme.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GastroApp.styles.css" asp-append-version="true" />

    <!--Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <!-- Alerts -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GastroApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Produkt" asp-action="Index">Produkty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Samochod" asp-action="Index">Samochody</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Pracownik" asp-action="Index">Pracownicy</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Kierowca"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Kierowca" asp-controller="Zamowienia" asp-action="Index">Zamówienia</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Kierowca" asp-controller="Samochod" asp-action="CreateZuzycie">Raport samochodu</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Kasjer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Kasjer" asp-controller="Zamowienia" asp-action="Index">Zamówienia</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Kasjer" asp-controller="NoweZamowienie" asp-action="ProduktyIndex">Dodaj zamówienie</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GastroApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GastroApp/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <script type="text/javascript">
        alertify.success('@TempData["success"]');
    </script>
}
@if (TempData["fail"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <script type="text/javascript">
        alertify.error('@TempData["fail"]');
    </script>
}